apiVersion: v1
data:
  config.json: '{"namespace": "dapr-demo", "workloads": [{"baseline": {"kind": "Deployment", "namespace":
    "dapr-demo", "name": "frontend"}, "baselineAppID": "frontend", "sandboxes": {"dapr-demo-frontend":
    "dapr-demo-frontend"}}, {"baseline": {"kind": "Deployment", "namespace": "dapr-demo", "name": "checkout"},
    "baselineAppID": "checkout", "sandboxes": {"dapr-demo-checkout": "dapr-demo-checkout"}}, {"baseline":
    {"kind": "Deployment", "namespace": "dapr-demo", "name": "order-processor"}, "baselineAppID": "order-processor",
    "sandboxes": {"dapr-demo-processor": "dapr-demo-processor"}}], "contexts": [{"id": "baseline", "label":
    "Baseline", "routingKey": null}, {"id": "frontend", "label": "Console sandbox", "routingKey": "v6mj1jq7xk4c4"},
    {"id": "checkout", "label": "Checkout sandbox", "routingKey": "nl9gdjqyfkvcy"}, {"id": "processor",
    "label": "Processor sandbox", "routingKey": "8r9c01wnw714w"}, {"id": "combined", "label": "Combined
    RouteGroup", "routingKey": "05dsb1fu3sy2w"}]}'
kind: ConfigMap
metadata:
  labels:
    tutorial.signadot.com/owner: 28e6d409-be1e-48a7-b636-7c29f750aee2
  name: tutorial-config
  namespace: dapr-demo
