apiVersion: v1
kind: Service
metadata:
  annotations:
    routing.signadot.com/ignore: 'true'
  labels:
    tutorial.signadot.com/owner: 28e6d409-be1e-48a7-b636-7c29f750aee2
  name: dapr-demo-checkout-dapr
  namespace: dapr-demo
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: dapr-demo-checkout-dep-checkout-b841a86e
    uid: aea802fb-e5d2-49c1-8a56-8339a70303bc
spec:
  externalName: dapr-demo-checkout-dep-checkout-2a8b3b8e.dapr-demo.svc.cluster.local
  ports:
  - name: dapr-internal
    port: 50002
    protocol: TCP
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    routing.signadot.com/ignore: 'true'
  labels:
    tutorial.signadot.com/owner: 28e6d409-be1e-48a7-b636-7c29f750aee2
  name: dapr-demo-processor-dapr
  namespace: dapr-demo
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: dapr-demo-processor-dep-order-processor-2cbcb292
    uid: 9a5a913f-57f7-474a-9646-1fc488f58593
spec:
  externalName: dapr-demo-processor-dep-order-processor-83122e5a.dapr-demo.svc.cluster.local
  ports:
  - name: dapr-internal
    port: 50002
    protocol: TCP
  type: ExternalName
